### ISSUE TITLE
Error during build (dotnet30)

### ISSUE THREAD

**Issue by ricoderks** [phnmnl/container-pwiz#6]
Hi all,

I'am trying to build the image and ran into problems with dotnet30. The output is:

```
------------------------------------------------------
Executing cd /home/xclient/.cache/winetricks/dotnet30
------------------------------------------------------
Installing .NET 3.0 runtime silently, as otherwise it gets hidden behind taskbar. Installation usually takes about 3 minutes.
------------------------------------------------------
Executing wine dotnetfx3.exe /q /c:install.exe /q
err:ole:CoGetClassObject class {acadf079-cbcd-4032-83f2-fa47c4db096f} not registered
err:ole:CoGetClassObject no class object {acadf079-cbcd-4032-83f2-fa47c4db096f} could be created for context 0x1

Error: Access denied
err:eventlog:ReportEventW L"System.ComponentModel.Win32Exception: Access denied\r\n   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)\r\n   at System.Diagnostics.Process.get_MainModule()\r\n   at System.ServiceModel.Install.MsiStyleLogWriter.CreateWriter()\r\n   at System.ServiceM"...
err:msi:ITERATE_Actions Execution halted, action L"DD_CA_InstallXwsRegExe_X86.3643236F_FC70_11D3_A536_0090278A1BB8" returned 1603

Error: Access denied
err:eventlog:ReportEventW L"System.ComponentModel.Win32Exception: Access denied\r\n   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)\r\n   at System.Diagnostics.Process.get_MainModule()\r\n   at System.ServiceModel.Install.MsiStyleLogWriter.CreateWriter()\r\n   at System.ServiceM"...
------------------------------------------------------
Note: command wine dotnetfx3.exe /q /c:install.exe /q returned status 67. Aborting.
------------------------------------------------------
The command '/bin/sh -c wine wineboot --init                 && /scripts/waitonprocess.sh wineserver                 && /usr/bin/xvfb-run winetricks --unattended dotnet35sp1                 && /scripts/waitonprocess.sh wineserver' returned a non-zero code: 1
```

Before I got this far I needed to make some small changes to be able to download msxml3. Shall I make a pull request for this?

Cheers, Rico

**Comment by sneumann** [comment]
Hi Rico, yes, if you have a fix just sned a PR. The other error you see is `Access denied`. IIRC that is because all current docker setups only have a sandboxing during `docker build`, which prevents some of the syscalls required during wine library installation. There are ugly workarounds https://github.com/moby/moby/issues/1916 but they are not yet tested (let alone documented) here for pwiz. Essentially, you `docker build` as far as you get, then `docker run --privileged` into it, do the steps that need the `--privileged` and `docker commit` the result. Happy to help, since the community really needs cross-plattform MS conversion. Yours, Steffen

**Comment by ricoderks** [comment]
Hi Steffen,

Thanks! Your right the community needs cross-platform MS conversion. I will have a go at it and try to document as much as of what I'am doing.  I'll let you know how it went / goes.

Cheers, Rico

**Comment by sneumann** [comment]
I think this was fixed long ago. Yours, Steffen
